CREATE DATABASE gustagram;
USE gustagram;

CREATE TABLE posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  texto TEXT NOT NULL,
  imagem_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  post_id INT NOT NULL,
  autor VARCHAR(100) DEFAULT 'Anônimo',
  texto TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
